# Generated by Django 6.0.4 on 2026-05-10 09:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('condition_type', models.CharField(choices=[('streak', 'Серия дней'), ('completion_count', 'Количество выполнений'), ('total_time', 'Суммарное время'), ('xp', 'Уровень XP'), ('custom', 'Кастомная логика')], default='streak', max_length=32)),
                ('condition_value', models.PositiveIntegerField(default=1)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('icon', models.CharField(blank=True, default='medal', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['condition_value'],
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('emoji', models.CharField(blank=True, default='', max_length=8)),
            ],
            options={
                'verbose_name': 'Тип активности',
                'verbose_name_plural': 'Типы активности',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('target_type', models.CharField(choices=[('check', 'check'), ('minutes', 'minutes'), ('count', 'count')], default='check', max_length=16)),
                ('target_value', models.PositiveIntegerField(default=1)),
                ('target_unit', models.CharField(choices=[('times', 'раз'), ('minutes', 'минут'), ('pages', 'страниц'), ('steps', 'шагов'), ('glasses', 'стаканов'), ('kilometers', 'км')], default='times', max_length=16)),
                ('color', models.CharField(choices=[('green', 'Зелёный'), ('blue', 'Синий'), ('orange', 'Оранжевый'), ('purple', 'Фиолетовый'), ('red', 'Красный'), ('pink', 'Розовый')], default='green', max_length=16)),
                ('icon', models.CharField(choices=[('spa', 'Йога'), ('dumbbell', 'Спорт'), ('book', 'Чтение'), ('water', 'Вода'), ('brain', 'Мышление'), ('heart', 'Здоровье'), ('code', 'Работа'), ('music', 'Музыка'), ('palette', 'Творчество'), ('leaf', 'Природа'), ('moon', 'Сон'), ('utensils', 'Питание')], default='spa', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_type', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'По дням недели'), ('monthly', 'Ежемесячно'), ('custom', 'Кастомно')], default='daily', max_length=16)),
                ('days_of_week', models.CharField(blank=True, default='1,2,3,4,5,6,7', max_length=32)),
                ('times_per_period', models.PositiveIntegerField(default=1)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='habits.habit')),
            ],
            options={
                'verbose_name': 'Расписание привычки',
                'verbose_name_plural': 'Расписания привычек',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('hint', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='habits.activitytype')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HabitTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.tag')),
            ],
            options={
                'unique_together': {('habit', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='habit',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='habits', through='habits.HabitTag', to='habits.tag'),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('condition_type', models.CharField(choices=[('completion_count', 'completion_count'), ('tag_completion_count', 'tag_completion_count'), ('streak', 'streak'), ('total_time', 'total_time'), ('custom', 'custom')], default='completion_count', max_length=32)),
                ('condition_value', models.PositiveIntegerField(default=1)),
                ('xp_reward', models.PositiveIntegerField(default=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='habits.tag')),
            ],
            options={
                'verbose_name': 'Челлендж',
                'verbose_name_plural': 'Челленджи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='habits.tagcategory')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('weak_day', 'Слабый день недели'), ('best_day', 'Лучший день недели'), ('streak', 'Серия выполнений'), ('tag_analytics', 'Аналитика по тегам'), ('mascot_message', 'Сообщение маскота'), ('custom', 'Кастом')], default='custom', max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Инсайт',
                'verbose_name_plural': 'Инсайты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('mascot_name', models.CharField(default='Хома', max_length=64)),
                ('mascot_mood', models.CharField(choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('excited', 'Excited')], default='happy', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('done', 'Выполнено'), ('partial', 'Частично'), ('skipped', 'Пропущено осознанно'), ('missed', 'Пропущено')], default='done', max_length=16)),
                ('value', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('mood_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись выполнения',
                'verbose_name_plural': 'Записи выполнения',
                'ordering': ['-log_date'],
                'unique_together': {('habit', 'log_date')},
            },
        ),
        migrations.CreateModel(
            name='TagCategoryWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_weights', to='habits.tagcategory')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_weights', to='habits.tag')),
            ],
            options={
                'verbose_name': 'Вес тега',
                'verbose_name_plural': 'Веса тегов',
                'unique_together': {('tag', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='habits.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершён'), ('failed', 'Провален'), ('cancelled', 'Отменён')], default='active', max_length=16)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='habits.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
