# Generated by Django 6.0.5 on 2026-05-07 20:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Системный код')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('condition_type', models.CharField(choices=[('streak', 'Серия дней'), ('completion_count', 'Количество выполнений'), ('total_time', 'Суммарное время'), ('xp', 'Количество XP'), ('custom', 'Своё условие')], max_length=30, verbose_name='Тип условия')),
                ('condition_value', models.IntegerField(verbose_name='Значение условия')),
                ('xp_reward', models.IntegerField(default=0, verbose_name='Награда XP')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Иконка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('condition_type', models.CharField(choices=[('completion_count', 'Количество выполнений'), ('tag_completion_count', 'Количество выполнений по тегу'), ('streak', 'Серия дней'), ('total_time', 'Суммарное время'), ('custom', 'Своё условие')], max_length=30, verbose_name='Тип условия')),
                ('condition_value', models.IntegerField(verbose_name='Значение условия')),
                ('xp_reward', models.IntegerField(default=0, verbose_name='Награда XP')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Челлендж',
                'verbose_name_plural': 'Челленджи',
                'db_table': 'challenges',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('target_type', models.CharField(choices=[('check', 'Отметка'), ('minutes', 'Минуты'), ('count', 'Количество')], default='check', max_length=20, verbose_name='Тип цели')),
                ('target_value', models.IntegerField(default=1, verbose_name='Целевое значение')),
                ('target_unit', models.CharField(blank=True, choices=[('times', 'раз(а)'), ('minutes', 'минут'), ('pages', 'страниц'), ('steps', 'шагов'), ('glasses', 'стаканов'), ('kilometers', 'километров')], max_length=20, verbose_name='Единица измерения')),
                ('color', models.CharField(default='#4CAF50', max_length=7, verbose_name='Цвет (HEX)')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'db_table': 'habits',
            },
        ),
        migrations.CreateModel(
            name='HabitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_type', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('custom', 'Своё')], default='daily', max_length=20, verbose_name='Тип частоты')),
                ('days_of_week', models.JSONField(blank=True, default=list, verbose_name='Дни недели (1-7)')),
                ('times_per_period', models.IntegerField(default=1, verbose_name='Количество раз за период')),
                ('reminder_time', models.TimeField(blank=True, null=True, verbose_name='Время напоминания')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='habits.habit', verbose_name='Привычка')),
            ],
            options={
                'verbose_name': 'Расписание привычки',
                'verbose_name_plural': 'Расписания привычек',
                'db_table': 'habit_schedules',
            },
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='habits.tagcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория тега',
                'verbose_name_plural': 'Категории тегов',
                'db_table': 'tag_categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='habits.tagcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('xp', models.IntegerField(default=0, verbose_name='Опыт (XP)')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Текущая серия')),
                ('best_streak', models.IntegerField(default=0, verbose_name='Лучшая серия')),
                ('mascot_name', models.CharField(blank=True, default='Хома', max_length=50, verbose_name='Имя маскота')),
                ('mascot_mood', models.CharField(choices=[('happy', 'Счастлив'), ('sad', 'Грустный'), ('neutral', 'Нейтральный')], default='neutral', max_length=20, verbose_name='Настроение маскота')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(verbose_name='Дата выполнения')),
                ('status', models.CharField(choices=[('done', 'Выполнено'), ('missed', 'Пропущено'), ('skipped', 'Осознанно пропущено'), ('partial', 'Частично')], default='done', max_length=20, verbose_name='Статус')),
                ('value', models.IntegerField(default=0, verbose_name='Фактическое значение')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='Потрачено минут')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Заметка')),
                ('mood_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка настроения (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit', verbose_name='Привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог привычки',
                'verbose_name_plural': 'Логи привычек',
                'db_table': 'habit_logs',
                'indexes': [models.Index(fields=['habit', 'log_date'], name='habit_logs_habit_i_8766dd_idx'), models.Index(fields=['user', 'log_date'], name='habit_logs_user_id_ba2612_idx')],
                'constraints': [models.UniqueConstraint(fields=('habit', 'log_date'), name='unique_habit_log_per_day')],
            },
        ),
        migrations.CreateModel(
            name='HabitTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_tags', to='habits.habit')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_tags', to='habits.tag')),
            ],
            options={
                'verbose_name': 'Связь привычки и тега',
                'verbose_name_plural': 'Связи привычек и тегов',
                'db_table': 'habit_tags',
                'constraints': [models.UniqueConstraint(fields=('habit', 'tag'), name='unique_habit_tag')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='habits.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'db_table': 'user_achievements',
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement')],
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершён'), ('failed', 'Провален'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Статус')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to='habits.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участие в челлендже',
                'verbose_name_plural': 'Участия в челленджах',
                'db_table': 'user_challenges',
                'constraints': [models.UniqueConstraint(fields=('user', 'challenge'), name='unique_user_challenge')],
            },
        ),
        migrations.CreateModel(
            name='UserInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('weak_day', 'Слабый день'), ('best_day', 'Лучший день'), ('streak', 'Серия'), ('tag_analytics', 'Аналитика по тегам'), ('mascot_message', 'Сообщение маскота'), ('custom', 'Своё')], max_length=30, verbose_name='Тип инсайта')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Доп. данные')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Начало периода')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Конец периода')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Инсайт пользователя',
                'verbose_name_plural': 'Инсайты пользователей',
                'db_table': 'user_insights',
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_insigh_user_id_d10422_idx')],
            },
        ),
    ]
