# Generated by Django 6.0.4 on 2026-05-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_seed_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitschedule',
            name='window_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitschedule',
            name='window_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
