# Generated by Django 6.0.4 on 2026-05-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_fix_notification_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('achievement', 'Достижение'), ('level_up', 'Повышение уровня'), ('streak', 'Серия'), ('system', 'Системное'), ('recommendation', 'Рекомендация')], default='achievement', max_length=24),
        ),
    ]
